/* The following code was generated by JFlex 1.4.3 on 15-11-15 ÏÂÎç9:41 */

package com.tang.intellij.lua.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import com.tang.intellij.lua.psi.LuaTypes;
import com.intellij.psi.TokenType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 15-11-15 ÏÂÎç9:41 from the specification file
 * <tt>E:/Git/IntelliJ-Lua/src/com/tang/intellij/lua/lua.flex</tt>
 */
class LuaLexer implements FlexLexer, LuaTypes {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int XLONGSTRING = 2;
  public static final int XSTRINGA = 12;
  public static final int XLONGCOMMENT = 8;
  public static final int XSHORTCOMMENT = 6;
  public static final int YYINITIAL = 0;
  public static final int XSTRINGQ = 10;
  public static final int XLONGSTRING_BEGIN = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6, 6
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\2\2\0\1\3\22\0\1\1\1\44\1\41\1\43"+
    "\1\0\1\51\1\0\1\42\1\53\1\54\1\50\1\10\1\60\1\16"+
    "\1\14\1\52\1\11\11\6\1\62\1\61\1\46\1\15\1\45\2\0"+
    "\4\13\1\7\1\13\21\5\1\12\2\5\1\4\1\64\1\55\1\63"+
    "\1\5\1\0\1\17\1\22\1\34\1\21\1\24\1\32\1\5\1\37"+
    "\1\31\1\5\1\25\1\27\1\5\1\20\1\26\1\36\1\5\1\23"+
    "\1\30\1\35\1\33\1\65\1\40\1\12\2\5\1\56\1\0\1\57"+
    "\1\47\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\7\0\1\1\1\2\1\3\1\4\1\5\1\6\1\5"+
    "\1\7\1\10\1\11\15\4\1\12\1\13\1\14\1\15"+
    "\1\16\1\1\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\3\33\1\34"+
    "\2\35\1\36\2\37\3\40\1\41\2\42\1\43\1\41"+
    "\2\44\1\43\1\41\1\45\2\0\1\5\1\0\1\5"+
    "\1\46\1\47\1\50\3\4\1\51\4\4\1\52\1\4"+
    "\1\53\1\54\7\4\1\55\1\56\1\57\1\60\1\0"+
    "\1\61\1\0\1\62\1\0\2\5\1\63\1\0\1\50"+
    "\1\64\1\65\1\66\3\4\1\67\3\4\1\70\5\4"+
    "\1\71\1\0\2\72\3\4\1\73\4\4\1\74\1\75"+
    "\1\4\2\0\1\76\3\4\1\77\1\100\1\4\1\101"+
    "\1\102\1\0\1\103\1\104\1\105\1\4\1\0\1\4"+
    "\1\106";

  private static int [] zzUnpackAction() {
    int [] result = new int[161];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\330\0\u010e\0\u0144\0\u017a"+
    "\0\u01b0\0\u01e6\0\u021c\0\u0252\0\u017a\0\u0288\0\u02be\0\u02f4"+
    "\0\u032a\0\u0360\0\u0396\0\u03cc\0\u0402\0\u0438\0\u046e\0\u04a4"+
    "\0\u04da\0\u0510\0\u0546\0\u057c\0\u05b2\0\u05e8\0\u017a\0\u017a"+
    "\0\u061e\0\u0654\0\u068a\0\u06c0\0\u017a\0\u017a\0\u017a\0\u017a"+
    "\0\u017a\0\u017a\0\u017a\0\u017a\0\u017a\0\u017a\0\u017a\0\u017a"+
    "\0\u017a\0\u06f6\0\u072c\0\u017a\0\u017a\0\u0762\0\u017a\0\u017a"+
    "\0\u0798\0\u017a\0\u07ce\0\u0804\0\u017a\0\u017a\0\u083a\0\u0870"+
    "\0\u08a6\0\u017a\0\u08dc\0\u0912\0\u0948\0\u017a\0\u01e6\0\u097e"+
    "\0\u09b4\0\u09ea\0\u0a20\0\u0a56\0\u017a\0\u0a8c\0\u0ac2\0\u0af8"+
    "\0\u0b2e\0\u021c\0\u0b64\0\u0b9a\0\u0bd0\0\u0c06\0\u021c\0\u0c3c"+
    "\0\u021c\0\u021c\0\u0c72\0\u0ca8\0\u0cde\0\u0d14\0\u0d4a\0\u0d80"+
    "\0\u0db6\0\u017a\0\u017a\0\u017a\0\u017a\0\u072c\0\u017a\0\u0804"+
    "\0\u017a\0\u0a20\0\u0dec\0\u09ea\0\u017a\0\u0e22\0\u0e58\0\u021c"+
    "\0\u021c\0\u021c\0\u0e8e\0\u0ec4\0\u0efa\0\u021c\0\u0f30\0\u0f66"+
    "\0\u0f9c\0\u021c\0\u0fd2\0\u1008\0\u103e\0\u1074\0\u10aa\0\u017a"+
    "\0\u10e0\0\u1116\0\u114c\0\u1182\0\u11b8\0\u11ee\0\u1224\0\u125a"+
    "\0\u1290\0\u12c6\0\u12fc\0\u021c\0\u021c\0\u1332\0\u1116\0\u1368"+
    "\0\u021c\0\u139e\0\u13d4\0\u140a\0\u021c\0\u021c\0\u1440\0\u021c"+
    "\0\u021c\0\u1476\0\u021c\0\u021c\0\u021c\0\u14ac\0\u14e2\0\u1518"+
    "\0\u021c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[161];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\10\3\11\1\12\1\13\1\14\1\13\1\15\1\16"+
    "\2\13\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\13\1\30\1\31\1\13\1\32\1\33"+
    "\1\34\1\13\1\35\2\13\1\36\1\37\1\40\1\41"+
    "\1\10\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\10\1\13\3\61\1\62\51\61\1\63\10\61\2\64"+
    "\1\65\1\66\62\64\2\67\1\70\1\71\62\67\3\72"+
    "\1\73\51\72\1\74\10\72\2\75\1\76\1\77\35\75"+
    "\1\100\22\75\1\101\3\75\1\102\1\103\36\75\1\104"+
    "\21\75\1\105\1\75\67\0\3\11\66\0\1\106\10\0"+
    "\1\107\55\0\3\13\1\0\3\13\3\0\22\13\24\0"+
    "\1\13\6\0\1\14\1\110\1\0\1\14\2\0\1\111"+
    "\7\0\1\110\47\0\1\14\1\110\1\0\1\14\1\112"+
    "\1\0\1\111\7\0\1\110\47\0\1\113\2\0\1\113"+
    "\2\0\1\114\66\0\1\115\66\0\1\116\54\0\3\13"+
    "\1\0\3\13\3\0\1\13\1\117\20\13\24\0\1\13"+
    "\5\0\3\13\1\0\3\13\3\0\7\13\1\120\2\13"+
    "\1\121\7\13\24\0\1\13\5\0\3\13\1\0\3\13"+
    "\3\0\7\13\1\122\12\13\24\0\1\13\5\0\3\13"+
    "\1\0\3\13\3\0\4\13\1\123\15\13\24\0\1\13"+
    "\5\0\3\13\1\0\3\13\3\0\5\13\1\124\14\13"+
    "\24\0\1\13\5\0\3\13\1\0\3\13\3\0\1\13"+
    "\1\125\6\13\1\126\11\13\24\0\1\13\5\0\3\13"+
    "\1\0\3\13\3\0\4\13\1\127\15\13\24\0\1\13"+
    "\5\0\3\13\1\0\3\13\3\0\7\13\1\130\12\13"+
    "\24\0\1\13\5\0\3\13\1\0\3\13\3\0\1\13"+
    "\1\131\11\13\1\132\6\13\24\0\1\13\5\0\3\13"+
    "\1\0\3\13\3\0\1\133\6\13\1\134\4\13\1\135"+
    "\5\13\24\0\1\13\5\0\3\13\1\0\3\13\3\0"+
    "\1\13\1\136\20\13\24\0\1\13\5\0\3\13\1\0"+
    "\3\13\3\0\4\13\1\137\13\13\1\140\1\13\24\0"+
    "\1\13\5\0\3\13\1\0\3\13\3\0\20\13\1\141"+
    "\1\13\24\0\1\13\44\0\1\142\36\0\1\143\65\0"+
    "\1\144\65\0\1\145\52\0\1\61\100\0\1\146\37\0"+
    "\1\147\12\0\1\65\65\0\1\70\65\0\1\72\100\0"+
    "\1\150\37\0\1\151\12\0\1\76\124\0\1\75\26\0"+
    "\1\75\1\0\1\75\12\0\2\75\1\0\2\75\6\0"+
    "\1\75\2\0\1\75\3\0\2\75\12\0\1\75\6\0"+
    "\2\75\2\0\1\102\125\0\1\75\25\0\1\75\1\0"+
    "\1\75\12\0\2\75\1\0\2\75\6\0\1\75\2\0"+
    "\1\75\4\0\1\75\12\0\1\75\6\0\2\75\6\0"+
    "\1\113\1\0\1\152\1\113\4\0\1\152\55\0\1\153"+
    "\2\0\1\153\62\0\2\154\1\0\1\154\1\0\1\154"+
    "\3\0\1\154\1\0\2\154\1\0\1\154\5\0\1\154"+
    "\1\0\1\154\37\0\1\113\2\0\1\113\70\0\1\155"+
    "\55\0\1\156\11\0\1\157\54\0\3\13\1\0\3\13"+
    "\3\0\2\13\1\160\17\13\24\0\1\13\5\0\3\13"+
    "\1\0\3\13\3\0\16\13\1\161\3\13\24\0\1\13"+
    "\5\0\3\13\1\0\3\13\3\0\10\13\1\162\11\13"+
    "\24\0\1\13\5\0\3\13\1\0\3\13\3\0\5\13"+
    "\1\163\14\13\24\0\1\13\5\0\3\13\1\0\3\13"+
    "\3\0\16\13\1\164\1\165\2\13\24\0\1\13\5\0"+
    "\3\13\1\0\3\13\3\0\2\13\1\166\17\13\24\0"+
    "\1\13\5\0\3\13\1\0\3\13\3\0\11\13\1\167"+
    "\10\13\24\0\1\13\5\0\3\13\1\0\3\13\3\0"+
    "\15\13\1\170\4\13\24\0\1\13\5\0\3\13\1\0"+
    "\3\13\3\0\10\13\1\171\11\13\24\0\1\13\5\0"+
    "\3\13\1\0\3\13\3\0\4\13\1\172\15\13\24\0"+
    "\1\13\5\0\3\13\1\0\3\13\3\0\1\13\1\173"+
    "\20\13\24\0\1\13\5\0\3\13\1\0\3\13\3\0"+
    "\16\13\1\174\3\13\24\0\1\13\5\0\3\13\1\0"+
    "\3\13\3\0\14\13\1\175\5\13\24\0\1\13\5\0"+
    "\3\13\1\0\3\13\3\0\5\13\1\176\14\13\24\0"+
    "\1\13\5\0\3\13\1\0\3\13\3\0\12\13\1\177"+
    "\7\13\24\0\1\13\6\0\1\153\1\110\1\0\1\153"+
    "\12\0\1\110\45\0\1\200\10\0\1\156\50\0\2\201"+
    "\1\202\1\203\12\201\1\157\47\201\5\0\3\13\1\0"+
    "\3\13\3\0\1\204\21\13\24\0\1\13\5\0\3\13"+
    "\1\0\3\13\3\0\14\13\1\205\5\13\24\0\1\13"+
    "\5\0\3\13\1\0\3\13\3\0\5\13\1\206\14\13"+
    "\24\0\1\13\5\0\3\13\1\0\3\13\3\0\5\13"+
    "\1\207\14\13\24\0\1\13\5\0\3\13\1\0\3\13"+
    "\3\0\1\210\21\13\24\0\1\13\5\0\3\13\1\0"+
    "\3\13\3\0\11\13\1\211\10\13\24\0\1\13\5\0"+
    "\3\13\1\0\3\13\3\0\15\13\1\212\4\13\24\0"+
    "\1\13\5\0\3\13\1\0\3\13\3\0\12\13\1\213"+
    "\7\13\24\0\1\13\5\0\3\13\1\0\3\13\3\0"+
    "\5\13\1\214\14\13\24\0\1\13\5\0\3\13\1\0"+
    "\3\13\3\0\1\13\1\215\20\13\24\0\1\13\5\0"+
    "\3\13\1\0\3\13\3\0\10\13\1\216\11\13\24\0"+
    "\1\13\2\201\1\202\1\203\62\201\1\0\1\217\14\0"+
    "\1\220\50\0\1\217\1\202\13\0\1\220\54\0\3\13"+
    "\1\0\3\13\3\0\6\13\1\221\13\13\24\0\1\13"+
    "\5\0\3\13\1\0\3\13\3\0\4\13\1\222\15\13"+
    "\24\0\1\13\5\0\3\13\1\0\3\13\3\0\1\223"+
    "\21\13\24\0\1\13\5\0\3\13\1\0\3\13\3\0"+
    "\12\13\1\224\7\13\24\0\1\13\5\0\3\13\1\0"+
    "\3\13\3\0\10\13\1\225\11\13\24\0\1\13\5\0"+
    "\3\13\1\0\3\13\3\0\5\13\1\226\14\13\24\0"+
    "\1\13\5\0\3\13\1\0\3\13\3\0\16\13\1\227"+
    "\3\13\24\0\1\13\5\0\3\13\1\0\3\13\3\0"+
    "\10\13\1\230\11\13\24\0\1\13\5\0\3\13\1\0"+
    "\3\13\3\0\5\13\1\231\14\13\24\0\1\13\16\0"+
    "\1\232\54\0\3\13\1\0\3\13\3\0\1\13\1\233"+
    "\20\13\24\0\1\13\5\0\3\13\1\0\3\13\3\0"+
    "\16\13\1\234\3\13\24\0\1\13\5\0\3\13\1\0"+
    "\3\13\3\0\13\13\1\235\6\13\24\0\1\13\5\0"+
    "\3\13\1\0\3\13\3\0\12\13\1\236\7\13\24\0"+
    "\1\13\2\201\1\202\1\203\1\237\61\201\5\0\3\13"+
    "\1\0\3\13\3\0\7\13\1\240\12\13\24\0\1\13"+
    "\2\0\1\202\1\203\67\0\3\13\1\0\3\13\3\0"+
    "\1\13\1\241\20\13\24\0\1\13";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5454];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\7\0\1\11\4\1\1\11\21\1\2\11\4\1\15\11"+
    "\2\1\2\11\1\1\2\11\1\1\1\11\2\1\2\11"+
    "\3\1\1\11\3\1\1\11\2\0\1\1\1\0\2\1"+
    "\1\11\24\1\4\11\1\0\1\11\1\0\1\11\1\0"+
    "\2\1\1\11\1\0\21\1\1\11\1\0\15\1\2\0"+
    "\11\1\1\0\4\1\1\0\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[161];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    ExtendedSyntaxStrCommentHandler longCommentOrStringHandler = new ExtendedSyntaxStrCommentHandler();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LuaLexer(java.io.Reader in) {
      this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 144) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 44: 
          { return IF;
          }
        case 71: break;
        case 70: 
          { return FUNCTION;
          }
        case 72: break;
        case 50: 
          { if (longCommentOrStringHandler.isCurrentExtQuoteStart(yytext())) {
                       yybegin(YYINITIAL); longCommentOrStringHandler.resetCurrentExtQuoteStart(); return LONGCOMMENT_END;
                       }  else { yypushback(yytext().length()-1); }
                        return LONGCOMMENT;
          }
        case 73: break;
        case 26: 
          { return EXP;
          }
        case 74: break;
        case 36: 
          { yybegin(YYINITIAL);return WRONG;
          }
        case 75: break;
        case 14: 
          { return LT;
          }
        case 76: break;
        case 37: 
          { longCommentOrStringHandler.setCurrentExtQuoteStart(yytext().toString()); yybegin( XLONGSTRING_BEGIN ); return LONGSTRING_BEGIN;
          }
        case 77: break;
        case 55: 
          { return END;
          }
        case 78: break;
        case 38: 
          { return CONCAT;
          }
        case 79: break;
        case 15: 
          { return MULT;
          }
        case 80: break;
        case 49: 
          { if (longCommentOrStringHandler.isCurrentExtQuoteStart(yytext())) {
                       yybegin(YYINITIAL); longCommentOrStringHandler.resetCurrentExtQuoteStart(); return LONGSTRING_END;
                       } else { yypushback(yytext().length()-1); }
                        return LONGSTRING;
          }
        case 81: break;
        case 3: 
          { return LBRACK;
          }
        case 82: break;
        case 28: 
          { yypushback(yytext().length()); yybegin(XLONGSTRING); return advance();
          }
        case 83: break;
        case 2: 
          { return TokenType.WHITE_SPACE;
          }
        case 84: break;
        case 20: 
          { return RBRACK;
          }
        case 85: break;
        case 12: 
          { return GETN;
          }
        case 86: break;
        case 68: 
          { return REPEAT;
          }
        case 87: break;
        case 51: 
          { return ELLIPSIS;
          }
        case 88: break;
        case 21: 
          { return LCURLY;
          }
        case 89: break;
        case 58: 
          { yypushback(1); /* TODO: Only pushback a newline */  return LUADOC_COMMENT;
          }
        case 90: break;
        case 5: 
          { return NUMBER;
          }
        case 91: break;
        case 16: 
          { return MOD;
          }
        case 92: break;
        case 22: 
          { return RCURLY;
          }
        case 93: break;
        case 64: 
          { return FALSE;
          }
        case 94: break;
        case 23: 
          { return COMMA;
          }
        case 95: break;
        case 7: 
          { return DOT;
          }
        case 96: break;
        case 29: 
          { return NL_BEFORE_LONGSTRING;
          }
        case 97: break;
        case 43: 
          { return IN;
          }
        case 98: break;
        case 42: 
          { return OR;
          }
        case 99: break;
        case 24: 
          { return SEMI;
          }
        case 100: break;
        case 17: 
          { return DIV;
          }
        case 101: break;
        case 34: 
          { yybegin(YYINITIAL); return WRONG;
          }
        case 102: break;
        case 30: 
          { return SHORTCOMMENT;
          }
        case 103: break;
        case 4: 
          { return NAME;
          }
        case 104: break;
        case 11: 
          { yybegin(XSTRINGA); return STRING;
          }
        case 105: break;
        case 25: 
          { return COLON;
          }
        case 106: break;
        case 53: 
          { return NOT;
          }
        case 107: break;
        case 52: 
          { return AND;
          }
        case 108: break;
        case 45: 
          { yybegin( XSHORTCOMMENT ); return SHEBANG;
          }
        case 109: break;
        case 32: 
          { return LONGCOMMENT;
          }
        case 110: break;
        case 8: 
          { return ASSIGN;
          }
        case 111: break;
        case 46: 
          { return GE;
          }
        case 112: break;
        case 35: 
          { yybegin(YYINITIAL); return STRING;
          }
        case 113: break;
        case 1: 
          { return WRONG;
          }
        case 114: break;
        case 69: 
          { return ELSEIF;
          }
        case 115: break;
        case 65: 
          { return UNTIL;
          }
        case 116: break;
        case 61: 
          { return THEN;
          }
        case 117: break;
        case 41: 
          { return DO;
          }
        case 118: break;
        case 13: 
          { return GT;
          }
        case 119: break;
        case 63: 
          { return LOCAL;
          }
        case 120: break;
        case 27: 
          { return LONGSTRING;
          }
        case 121: break;
        case 59: 
          { return ELSE;
          }
        case 122: break;
        case 57: 
          { longCommentOrStringHandler.setCurrentExtQuoteStart(yytext().toString()); yybegin( XLONGCOMMENT ); return LONGCOMMENT_BEGIN;
          }
        case 123: break;
        case 67: 
          { return RETURN;
          }
        case 124: break;
        case 66: 
          { return WHILE;
          }
        case 125: break;
        case 48: 
          { return NE;
          }
        case 126: break;
        case 9: 
          { return MINUS;
          }
        case 127: break;
        case 10: 
          { yybegin(XSTRINGQ);  return STRING;
          }
        case 128: break;
        case 54: 
          { return NIL;
          }
        case 129: break;
        case 31: 
          { yybegin(YYINITIAL);  yypushback(yytext().length()); return advance();
          }
        case 130: break;
        case 33: 
          { return STRING;
          }
        case 131: break;
        case 60: 
          { return TRUE;
          }
        case 132: break;
        case 56: 
          { return FOR;
          }
        case 133: break;
        case 18: 
          { return LPAREN;
          }
        case 134: break;
        case 62: 
          { return BREAK;
          }
        case 135: break;
        case 40: 
          { yypushback(yytext().length()); yybegin( XSHORTCOMMENT ); return advance();
          }
        case 136: break;
        case 19: 
          { return RPAREN;
          }
        case 137: break;
        case 39: 
          { return EQ;
          }
        case 138: break;
        case 6: 
          { return PLUS;
          }
        case 139: break;
        case 47: 
          { return LE;
          }
        case 140: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
