{
  parserClass="com.tang.intellij.lua.doc.parser.LuaDocParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="LuaDoc"
  psiImplClassSuffix="Impl"
  psiPackage="com.tang.intellij.lua.doc.psi"
  psiImplPackage="com.tang.intellij.lua.doc.psi.impl"
  parserUtilClass="com.tang.intellij.lua.psi.LuaParserUtil"
  elementTypeHolderClass="com.tang.intellij.lua.doc.psi.LuaDocTypes"
  elementTypeClass="com.tang.intellij.lua.doc.psi.LuaDocElementType"
  tokenTypeClass="com.tang.intellij.lua.doc.psi.LuaDocTokenType"

  tokens = [
  ID = 'ID'
  AT = '@'
  EQ = '='
  LDOC_COMMENT_START = 'LDOC_COMMENT_START'
  LDOC_DASHES = 'LDOC_DASHES'
  ]
}

doc ::= LDOC_COMMENT_START tag_pair*

tag_name ::= ID
tag_value ::= ID
tag_pair ::= LDOC_COMMENT_START AT tag_name '=' tag_value { pin = 2 }